name: Deploy to GCP (Cloud Run, me-central2)

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "Dockerfile"
      - ".github/workflows/deploy-gcp.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: ${{ vars.PROJECT_ID }}
  REGION: ${{ vars.REGION }}
  REPO: ${{ vars.AR_REPO }}
  SERVICE: ${{ vars.SERVICE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Auth to GCP (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github
          service_account: github-deployer@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
      - uses: google-github-actions/setup-gcloud@v2
      - name: Build & push image
        run: |
          gcloud builds submit --tag ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/oaktree-estimator:${GITHUB_SHA}
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${SERVICE} \
            --image ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/oaktree-estimator:${GITHUB_SHA} \
            --region ${REGION} --allow-unauthenticated --port 8000 \
            --add-cloudsql-instances ${PROJECT_ID}:${REGION}:oaktree-sql \
            --set-env-vars "CLOUD_SQL_CONNECTION_NAME=${PROJECT_ID}:${REGION}:oaktree-sql,POSTGRES_USER=oaktree,POSTGRES_DB=oaktree,POSTGRES_HOST=/cloudsql/${PROJECT_ID}:${REGION}:oaktree-sql,POSTGRES_PORT=5432" \
            --set-secrets "POSTGRES_PASSWORD=DB_PASSWORD:latest"
