name: Prefetch offline map tiles

on:
  workflow_dispatch:
    inputs:
      bbox:
        description: "minLon,minLat,maxLon,maxLat"
        required: true
        default: "46.20,24.20,47.30,25.10"
      zooms:
        description: "Zooms (range or list)"
        required: true
        default: "17-19"
      dest:
        description: "Destination folder"
        required: true
        default: "frontend/public/static-tiles"

jobs:
  fetch:
    runs-on: ubuntu-latest
    timeout-minutes: 310            # hard GitHub cap ~6h; we finish well before 5h10m
    permissions:
      contents: write               # needed to push commits
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - name: Prefetch tiles with periodic commits
        run: |
          # leave ~25 minutes from the 5h10m job limit for safety
          DEADLINE_SECS=$(( (310*60) - (25*60) ))
          python scripts/prefetch_tiles.py \
            --bbox "${{ github.event.inputs.bbox }}" \
            --zooms "${{ github.event.inputs.zooms }}" \
            --dest "${{ github.event.inputs.dest }}" \
            --checkpoint-secs 600 \
            --deadline-secs "${DEADLINE_SECS}"
